[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/events"
  to = "/.netlify/functions/events"
  status = 200

[[redirects]]
  from = "/api/event"
  to = "/.netlify/functions/event"
  status = 200
